### ISSUE TITLE
I changed to version 3.7 and I'm still stuck at this point. No matter how I solve it (with the help of chatgpt), I can't download catboost.

### ISSUE THREAD

**Issue by Demonpzh** [CoDS-GCS/kgpip-public#3]
f776
  Stored in directory: /private/var/folders/jq/3x3xv2ld5mgd27368fjdgypc0000gn/T/pip-ephem-wheel-cache-recrd_2t/wheels/c5/56/cc/e33d4a8cb4ffeb040d59ea08c4715d20806945dc80d3c25384
  Building wheel for spacy-universal-sentence-encoder (setup.py) ... done
  Created wheel for spacy-universal-sentence-encoder: filename=spacy_universal_sentence_encoder-0.4.6-py3-none-any.whl size=16537 sha256=13c3f354b017c40f912a497d68fcb0b27ebea69ea72714465f536bf53aef0e92
  Stored in directory: /private/var/folders/jq/3x3xv2ld5mgd27368fjdgypc0000gn/T/pip-ephem-wheel-cache-recrd_2t/wheels/6c/27/98/2ff864e0b7104d378217f5c04de66dc836e0bdb172e888552e
  Building wheel for eden-kernel (setup.py) ... done
  Created wheel for eden-kernel: filename=eden_kernel-0.0.0-py3-none-any.whl size=44910 sha256=a865234a19c7a3d0c33636330061b984b5bac2d39874304e2ebb88cd56b522de
  Stored in directory: /private/var/folders/jq/3x3xv2ld5mgd27368fjdgypc0000gn/T/pip-ephem-wheel-cache-recrd_2t/wheels/d2/cd/36/69766fdf1ca886ab9821a68896a1f5938bb3158cd66f25ad20
  Building wheel for swifter (setup.py) ... done
  Created wheel for swifter: filename=swifter-1.4.0-py3-none-any.whl size=16506 sha256=675f0f2ae8dd0700daa6b7d336cd616f9bf882ff8d540afff842e18d4704dea5
  Stored in directory: /private/var/folders/jq/3x3xv2ld5mgd27368fjdgypc0000gn/T/pip-ephem-wheel-cache-recrd_2t/wheels/32/d7/b2/ac991019ad6a737c7bffeb58d9451532be276d951957156872
  Building wheel for catboost (pyproject.toml) ... |

**Comment by Demonpzh** [comment]
I changed catboost version solved the problem。pip install --no-cache-dir -r requirements.txt。Successfully installed ConfigSpace-0.4.21 FLAML-0.6.3 SPARQLWrapper-1.8.5 absl-py-2.1.0 astunparse-1.6.3 auto-sklearn-0.14.0 bitstring-3.1.9 cachetools-5.5.0 cloudpickle-2.2.1 colorama-0.4.6 dask-2021.6.2 decorator-5.1.1 dill-0.3.7 distributed-2021.6.2 eden-kernel-0.0.0 emcee-3.1.6 flatbuffers-24.3.25 fsspec-2023.1.0 gast-0.4.0 google-auth-2.36.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.62.3 h5py-3.8.0 heapdict-1.0.1 importlib-metadata-4.13.0 isodate-0.6.1 joblib-1.3.2 keras-2.11.0 liac-arff-2.5.0 libclang-18.1.1 lightgbm-4.5.0 locket-1.0.0 markdown-3.4.4 mindware-0.5.0 msgpack-1.0.5 natsort-8.4.0 networkx-2.2 nose-1.3.7 numpy-1.21.2 oauthlib-3.2.2 openbox-0.8.4 opt-einsum-3.3.0 partd-1.4.1 patsy-1.0.1 platypus-opt-1.0.4 prettytable-3.7.0 protobuf-3.19.6 psutil-6.1.0 pyaml-23.5.8 pyasn1-0.5.1 pyasn1-modules-0.3.0 pyemd-1.0.0 pynisher-1.0.10 pyrfr-0.8.3 pyyaml-6.0.1 rdflib-6.3.2 requests-oauthlib-2.0.0 rsa-4.9 scikit-learn-0.24.2 scikit-optimize-0.9.0 scipy-1.7.1 smac-1.2 sortedcontainers-2.4.0 spacy-universal-sentence-encoder-0.4.6 statsmodels-0.13.5 swifter-1.4.0 tabulate-0.9.0 tblib-2.0.0 tensorboard-2.11.2 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.11.0 tensorflow-estimator-2.11.0 tensorflow-hub-0.16.0 tensorflow-io-gcs-filesystem-0.34.0 termcolor-2.3.0 terminaltables-3.1.10 threadpoolctl-3.1.0 toolz-0.12.1 tornado-6.2 wcwidth-0.2.13 werkzeug-2.2.3 wrapt-1.16.0 xgboost-1.3.3 zict-2.2.0。

**Comment by Demonpzh** [comment]
![Uploading 截屏2024-11-22 22.05.41.png…]()

**Comment by mossadhelali** [comment]
Hi @Demonpzh , thanks for trying out KGpip. The problem was that some libraries were updated after we published the project, which broke the libraries that depend on them: Specifically, `spacy` and `pynisher`. I have fixed the issue by specifying the correct versions in `requirements.txt`. This should solve both your issues. 

Please remove the current conda environment you have by running:
```
conda remove -n kgpip
```
Then cloning the latest version of the repo (in the `kgpip-public` directory):
```
git pull 
```

Then running  `init.sh` or `init-cpu.sh` based on your system.

Please let me know if this fixed your issues.

**Comment by Demonpzh** [comment]
When downloading and running catboost, it requires version >= 0.23. It will automatically download version 1.27. At this time, an error will still occur. However, when I specify to download catboost==0.26, the download is successful and the Quickstart code can be run correctly.

> 你好@Demonpzh，感谢您试用 KGpip。问题是我们发布项目后更新了一些库，这破坏了依赖它们的库：具体来说，`spacy`和`pynisher`。我已通过在中指定正确的版本解决了该问题`requirements.txt`。这应该可以解决您的两个问题。
> 
> 请通过运行以下命令删除您当前的 conda 环境：
> 
> ```
> conda remove -n kgpip
> ```
> 
> 然后克隆 repo 的最新版本（在`kgpip-public`目录中）：
> 
> ```
> git pull 
> ```
> 
> 然后运行 `init.sh`或`init-cpu.sh`基于您的系统。
> 
> 请让我知道这是否解决了您的问题。

**Comment by Demonpzh** [comment]
=== 2024-11-24 22:21:10.450260 === Regression? False === Time Budget: 300 === Graph Gen Model: /Users/pengzh/kgpip-public/training_artifacts/graph_generation/graph_generation_model.dat === Optimizer: autosklearn === Num Graphs: 5 ===
100%|██████████| 8/8 [00:00<00:00, 47.74it/s]
2024-11-24 22:21:10.627369 Closest Dataset is: flavours-of-physics
2024-11-24 22:21:25.831833 Using Graphs generated at: tmp/pipeline_graphs_94926091/
2024-11-24 22:21:26.023949 Considering 5 Skeletons: [(['no_preprocessing'], ['gradient_boosting']), (['no_preprocessing'], ['random_forest']), (['no_preprocessing'], ['sgd']), (['no_preprocessing'], ['extra_trees']), (['select_percentile'], ['extra_trees'])]
2024-11-24 22:21:26.023995 Time budget per graph: 57
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-24 22:21:29.981773 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['gradient_boosting']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-24 22:21:37.626445 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['random_forest']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-24 22:21:45.236244 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['sgd']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-24 22:21:52.834250 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['extra_trees']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-24 22:22:00.336566 AutoML automl_model failed: Pre-processors ['select_percentile'] Estimators: ['extra_trees']
The provided component 'select_percentile' for the key 'feature_preprocessor' in the 'include' argument is not valid. The supported components for the step 'feature_preprocessor' for this task are ['densifier', 'extra_trees_preproc_for_classification', 'fast_ica', 'feature_agglomeration', 'kernel_pca', 'kitchen_sinks', 'liblinear_svc_preprocessor', 'no_preprocessing', 'nystroem_sampler', 'pca', 'polynomial', 'random_trees_embedding', 'select_percentile_classification', 'select_rates_classification', 'truncatedSVD']
2024-11-24 22:22:00.336645 Fitting Done. Best Score: -1 . Best Skeleton: None
Traceback (most recent call last):
  File "/Users/pengzh/kgpip-public/learn.py", line 25, in <module>
    main()
  File "/Users/pengzh/kgpip-public/learn.py", line 20, in main
    predictions = kgpip.predict(X_test)
  File "/Users/pengzh/kgpip-public/kgpip.py", line 372, in predict
    return self.automl_model.predict(X_test)
AttributeError: 'NoneType' object has no attribute 'predict'

```
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from kgpip import KGpip


def main():
    # load and split the dataset
    df = pd.read_csv('benchmark_datasets/abalone/abalone.csv')
    X, y = df.drop('class', axis=1), df['class']
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,
                                                        random_state=123)

    # fit KGpip
    kgpip = KGpip(num_graphs=5, hpo='autosklearn', time_budget=300)
    kgpip.fit(X_train, y_train, task='classification')
    predictions = kgpip.predict(X_test)
    print('Score:', f1_score(y_test, predictions, average='macro'))


if __name__ == '__main__':
    main()

An error occurred when hpo was replaced with autosklearn, I want to know what the problem is

**Comment by Demonpzh** [comment]
I solved the problem by modifying memory_limit in kgpip's fit function code. Many thanks to the author for his help. I would like to ask the author whether he thinks a better meta-learning system can guide Bayesian optimization to find a better pipeline, whether it is expressed in f1score or acc

**Comment by mossadhelali** [comment]
> Hi @Demonpzh , thanks for trying out KGpip. The problem was that some libraries were updated after we published the project, which broke the libraries that depend on them: Specifically, `spacy` and `pynisher`. I have fixed the issue by specifying the correct versions in `requirements.txt`. This should solve both your issues.
> 
> Please remove the current conda environment you have by running:
> 
> ```
> conda remove -n kgpip
> ```
> 
> Then cloning the latest version of the repo (in the `kgpip-public` directory):
> 
> ```
> git pull 
> ```
> 
> Then running `init.sh` or `init-cpu.sh` based on your system.
> 
> Please let me know if this fixed your issues.

@Demonpzh , Thanks for letting me know about catboost. I will update `requirements.txt` accordingly.

**Comment by mossadhelali** [comment]
> === 2024-11-24 22:21:10.450260 === Regression? False === Time Budget: 300 === Graph Gen Model: /Users/pengzh/kgpip-public/training_artifacts/graph_generation/graph_generation_model.dat === Optimizer: autosklearn === Num Graphs: 5 === 100%|██████████| 8/8 [00:00<00:00, 47.74it/s] 2024-11-24 22:21:10.627369 Closest Dataset is: flavours-of-physics 2024-11-24 22:21:25.831833 Using Graphs generated at: tmp/pipeline_graphs_94926091/ 2024-11-24 22:21:26.023949 Considering 5 Skeletons: [(['no_preprocessing'], ['gradient_boosting']), (['no_preprocessing'], ['random_forest']), (['no_preprocessing'], ['sgd']), (['no_preprocessing'], ['extra_trees']), (['select_percentile'], ['extra_trees'])] 2024-11-24 22:21:26.023995 Time budget per graph: 57 Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. 2024-11-24 22:21:29.981773 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['gradient_boosting'] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. 2024-11-24 22:21:37.626445 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['random_forest'] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. 2024-11-24 22:21:45.236244 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['sgd'] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. 2024-11-24 22:21:52.834250 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['extra_trees'] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/**init**.py", line 346, in run\n obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module 'pynisher' has no attribute 'enforce_limits'\n', 'error': 'AttributeError("module 'pynisher' has no attribute 'enforce_limits'")'}. 2024-11-24 22:22:00.336566 AutoML automl_model failed: Pre-processors ['select_percentile'] Estimators: ['extra_trees'] The provided component 'select_percentile' for the key 'feature_preprocessor' in the 'include' argument is not valid. The supported components for the step 'feature_preprocessor' for this task are ['densifier', 'extra_trees_preproc_for_classification', 'fast_ica', 'feature_agglomeration', 'kernel_pca', 'kitchen_sinks', 'liblinear_svc_preprocessor', 'no_preprocessing', 'nystroem_sampler', 'pca', 'polynomial', 'random_trees_embedding', 'select_percentile_classification', 'select_rates_classification', 'truncatedSVD'] 2024-11-24 22:22:00.336645 Fitting Done. Best Score: -1 . Best Skeleton: None Traceback (most recent call last): File "/Users/pengzh/kgpip-public/learn.py", line 25, in main() File "/Users/pengzh/kgpip-public/learn.py", line 20, in main predictions = kgpip.predict(X_test) File "/Users/pengzh/kgpip-public/kgpip.py", line 372, in predict return self.automl_model.predict(X_test) AttributeError: 'NoneType' object has no attribute 'predict'
> 
> ```
> import pandas as pd
> from sklearn.model_selection import train_test_split
> from sklearn.metrics import f1_score
> from kgpip import KGpip
> 
> 
> def main():
>     # load and split the dataset
>     df = pd.read_csv('benchmark_datasets/abalone/abalone.csv')
>     X, y = df.drop('class', axis=1), df['class']
>     X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,
>                                                         random_state=123)
> 
>     # fit KGpip
>     kgpip = KGpip(num_graphs=5, hpo='autosklearn', time_budget=300)
>     kgpip.fit(X_train, y_train, task='classification')
>     predictions = kgpip.predict(X_test)
>     print('Score:', f1_score(y_test, predictions, average='macro'))
> 
> 
> if __name__ == '__main__':
>     main()
> 
> An error occurred when hpo was replaced with autosklearn, I want to know what the problem is
> ```

@Demonpzh , This error happens because `pynisher` librabry needs to be in version `0.6.4`. You need to install it via `pip install pynisher==0.6.4`.

**Comment by mossadhelali** [comment]
> I solved the problem by modifying memory_limit in kgpip's fit function code. Many thanks to the author for his help. I would like to ask the author whether he thinks a better meta-learning system can guide Bayesian optimization to find a better pipeline, whether it is expressed in f1score or acc

Yes, generally, research in AutoML systems improve either meta-learning or hyperparameter optimization. So, having a better meta-learning algorithm will generally improve the score.

**Comment by Demonpzh** [comment]
2024-11-26 01:46:34.136277 Considering 5 Skeletons: [(['no_preprocessing'], ['gradient_boosting']), (['no_preprocessing'], ['adaboost']), (['no_preprocessing'], ['random_forest']), (['no_preprocessing'], ['sgd']), (['no_preprocessing'], ['extra_trees'])]
Sorry, I may have another question, why are Considering Skeletons all no_preprocessing? Is there something wrong with my code settings?

**Comment by mossadhelali** [comment]
These are the top 5 skeletons based on the number of graphs generated and
the allowed time budget. There is nothing wrong with your code, if you
increase these two parameters, you will see different preprocessors.

Mossad

**Comment by Demonpzh** [comment]
ok thank you very much again
