### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by Demonpzh** [CoDS-GCS/kgpip-public#4]
When I use hpo as flaml, it can run normally according to the Quickstart code。But some errors occurred when I changed hpo to autosklearn. Is there something wrong with my code?
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from kgpip import KGpip

def main():
    # load and split the dataset
    df = pd.read_csv('benchmark_datasets/abalone/abalone.csv')
    X, y = df.drop('class', axis=1), df['class']
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,
                                                        random_state=123)

    # fit KGpip
    kgpip = KGpip(num_graphs=5, hpo='autosklearn', time_budget=300)
    kgpip.fit(X_train, y_train, task='classification')
    predictions = kgpip.predict(X_test)

    # calculate accuracy
    print('Accuracy:', accuracy_score(y_test, predictions))

if __name__ == '__main__':
    main()
=== 2024-11-22 22:49:27.835940 === Regression? False === Time Budget: 300 === Graph Gen Model: /Users/pengzh/kgpip-public/training_artifacts/graph_generation/graph_generation_model.dat === Optimizer: autosklearn === Num Graphs: 5 ===
100%|██████████| 8/8 [00:00<00:00, 47.70it/s]
2024-11-22 22:49:28.014160 Closest Dataset is: flavours-of-physics
2024-11-22 22:49:42.772382 Using Graphs generated at: tmp/pipeline_graphs_48979874/
2024-11-22 22:49:42.981770 Considering 5 Skeletons: [(['no_preprocessing'], ['gradient_boosting']), (['no_preprocessing'], ['random_forest']), (['no_preprocessing'], ['sgd']), (['no_preprocessing'], ['extra_trees']), (['no_preprocessing'], ['k_nearest_neighbors'])]
2024-11-22 22:49:42.981817 Time budget per graph: 57
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:49:46.647215 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['gradient_boosting']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:49:54.248405 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['random_forest']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:50:01.832017 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['sgd']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:50:09.534415 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['extra_trees']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:50:17.149214 AutoML automl_model failed: Pre-processors ['no_preprocessing'] Estimators: ['k_nearest_neighbors']
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
2024-11-22 22:50:17.149242 Fitting Done. Best Score: -1 . Best Skeleton: None
Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/Users/pengzh/anaconda3/envs/py37/lib/python3.7/site-packages/autosklearn/evaluation/__init__.py", line 346, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
Traceback (most recent call last):
  File "/Users/pengzh/kgpip-public/learn.py", line 24, in <module>
    main()
  File "/Users/pengzh/kgpip-public/learn.py", line 17, in main
    predictions = kgpip.predict(X_test)
  File "/Users/pengzh/kgpip-public/kgpip.py", line 372, in predict
    return self.automl_model.predict(X_test)
AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by mossadhelali** [comment]
Hi @Demonpzh , thanks for trying out KGpip. The problem was that some libraries were updated after we published the project, which broke the libraries that depend on them: Specifically, `spacy` and `pynisher`. I have fixed the issue by specifying the correct versions in `requirements.txt`. This should solve both your issues. 

Please remove the current conda environment you have by running:
```
conda remove -n kgpip
```
Then cloning the latest version of the repo (in the `kgpip-public` directory):
```
git pull 
```

Then running  `init.sh` or `init-cpu.sh` based on your system.

Please let me know if this fixed your issues.
